USE UNIVER;

select STUDENT.NAME,
       FACULTY.FACULTY,
       PULPIT.PULPIT,
       PROFESSION.PROFESSION_NAME,
       SUBJECT.SUBJECT_NAME,
       case
           when (PROGRESS.NOTE = 6) then 'шесть'
           when (PROGRESS.NOTE = 7) then 'семь'
           when (PROGRESS.NOTE = 8) then 'восемь'
           end [Oценка]
from PROGRESS
          join STUDENT on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
          join SUBJECT on SUBJECT.SUBJECT = PROGRESS.SUBJECT
          join GROUPS on GROUPS.IDGROUP = STUDENT.IDGROUP
          join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
          join PULPIT on PULPIT.PULPIT = SUBJECT.PULPIT
          join FACULTY on FACULTY.FACULTY = PULPIT.FACULTY
where PROGRESS.NOTE between 6 and 8
order by (
CASE
	WHEN(PROGRESS.NOTE=7) THEN 1
	WHEN(PROGRESS.NOTE=8) THEN 2
	WHEN(PROGRESS.NOTE=6) THEN 3
	ELSE 4
END
)
