USE UNIVER;

SELECT * FROM 
	PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT =TEACHER.PULPIT

SELECT * FROM 
	PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT =TEACHER.PULPIT
	WHERE TEACHER.TEACHER IS NOT NULL

SELECT * FROM 
	PULPIT FULL OUTER JOIN TEACHER
	ON PULPIT.PULPIT =TEACHER.PULPIT
	WHERE TEACHER.TEACHER IS NULL